server:
  port: 8999

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI4Fn9Q8Ld4NhVrShy9LZo
      keysecret: HPzReljzlV0be78a35z8eLrjqcMgNV
      bucketname: cksspk-work
      expireTime: 30  #过期时间
      dir: alidemo/
      max: 1048576000
      min: 0
      callbackHost: www.cksspk.site #回调地址
      callBackInterFace: /api/aliOss/callback  #回调接口